config/routes.rb
Rails.application.routes.draw do
  
  resources :contacts, only: [:new, :create]
  
  root "static_pages#home"
  
  get '/home', to: 'static_pages#home'

  get '/committees', to: 'static_pages#committees'

  get '/registration', to: 'static_pages#registration'

  get '/schedule', to: 'static_pages#schedule'

  get '/studyguide', to: 'static_pages#studyguide'
   
  get '/contact', to: 'contacts#new'
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha => true
  
 #Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form",
      :to => "mayya.rohan@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact=Contact.new
  end
  
  def create
    @contact=Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = "Could not send message"
      render :new
    end
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def committees
  end

  def registration
  end

  def schedule
  end

  def studyguide
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/create.html.erb
<div class="contact-details">
<div class= "container">
  <div class="row">
    
    
    
    <div class="col-xs-6"><!--map location-->
    <div class="google-maps">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3888.0962601324654!2d77.60648701482191!3d12.965691890859805!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x8b64970e8e73174d!2sThe+Cathedral+High+School!5e0!3m2!1sen!2sin!4v1495699146258"  frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    </div>


    <div class="col-xs-6"><!--contact details-->
      <h4>The Cathedral High School</h4>
        <p>63, Richmond Rd, Shanthala Nagar, Muniswamy Garden, Neelasandra, Bengaluru, Karnataka 560025</p>
        <p> Contact number : 080 2557 2656</p>
    </div>
    
      </div>
</div>
</div>



<div align="center">
  <div class="section-heading text-center">
  <h3 class="h-bold">Thank you for your message!</h3>
  <div class="divider-header"></div>
  <p>We will get back to you soon.</p>
          </div>
          
         

app/views/contacts/new.html.erb
<%= provide(:title, "Contact Us") %>


<div class="contact-details">
<div class= "container">
  <div class="row">
    
    
    
    <div class="col-xs-6"><!--map location-->
    <div class="google-maps">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3888.0962601324654!2d77.60648701482191!3d12.965691890859805!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x8b64970e8e73174d!2sThe+Cathedral+High+School!5e0!3m2!1sen!2sin!4v1495699146258"  frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    </div>


    <div class="col-xs-6"><!--contact details-->
      <h4>The Cathedral High School</h4>
        <p>63, Richmond Rd, Shanthala Nagar, Muniswamy Garden, Neelasandra, Bengaluru, Karnataka 560025</p>
        <p> Contact number : 080 2557 2656</p>
    </div>
    
      </div>
</div>
</div>
    


<div align="center">
  
  <div class="section-heading text-center">
  <h3 class="h-bold contact-title" id="contact-bold">Send us a message!</h3>
  <div class="divider-header"></div><br><br><br><br>
          </div>
  
  
  <div class="container">
    
  <%= form_for @contact, :html => { class: 'form-horizontal center' } do |f| %>
    <div class="row">
        <div class="col-xs-12">
  <div class="form-group">
    <%= f.label :name, class: "control-label" %><br>
   
    <%= f.text_field :name, :required => true, class: "form-control" %>
    </div>
    </div>
    <br>
      
      <div class="col-xs-12">
    <div class="form-group">
    <%= f.label :email, class: "control-label" %><br>
    
    <%= f.email_field :email, :required => true, class: "form-control" %>
    </div>
    </div>
    <br>
    
      <div class="col-xs-12">
    <div class="form-group">
      
    <%= f.label :message, class: "control-label" %><br>
    <%= f.text_area :message, :as => :text, :required => true, class: "form-control" %>
    </div>
    </div>
    
    
    
    
    <div class= "hidden">
      <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
    </div>
    
    
      <div>
      <%= f.submit 'Send message', class: "btn btn-default marginbot-100 submit-button" %>
     </div>
     </div>
     
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<!--footer-->
<footer>
<div class="container">
  <div class="row">
      <div class="col-md-6 pull-left">
      <p>&copy; The Cathedral High School</p>
      <p>Coded with <i class="fa fa-heart" aria-hidden="true"></i> by Rohan Mayya</p>
  </div>

    <div class="col-md-6 text-right">
    <i class="fa fa-facebook fa-2x"></i>
    </div>

  </div><!--end row-->
  </div><!--end container-->
</footer>

app/views/layouts/_header.html.erb
    <!-- hero section -->

<section class="hero" id="intro">
            <div class="container">
              <div class="row">
                <div class="col-md-12 text-right navicon">
                  <a id="nav-toggle" class="nav_slide_button" href="#"><span></span></a>
                </div>
              </div>
              <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center inner">
                  
                        <h1>Cathedral High School Model UN 2017</h1>
                        <p>Power. Possibility. Peace.</p>
                    
               </div>
              </div>
              <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center">
                  <a href="#about" class="learn-more-btn btn-scroll">Learn more</a>
                </div>
              </div>
            </div>
    </section>
    
    <!-- end hero -->
    
    <!--navbar-->
    <div id="navigation">
    <nav class="navbar navbar-custom" role="navigation">
  <div class="container-fluid">
    <div class="row">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
          <div class="col-md-2">
          <%=link_to "CHSMUN", root_path, :class => 'navbar-brand' %>
          </div>
    </div>
        <div class="col-md-10">
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
            <li><%=link_to "Home", root_path %></li>
            <li><%=link_to "Committees", committees_path %></li>
            <li><%=link_to "Registration", registration_path %></li>
            <li><%=link_to "Schedule", schedule_path %></li>
            <li><%=link_to "StudyGuides", studyguide_path %></li>
            <li><%=link_to "Contact", contact_path %></li>
          </ul>
        </div>

      </div>
      </div>
    </nav>
    </div>
  <!--end navbar-->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | CHSMUN '17</title>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/shim' %>
    
  </head>


  <body id="page-top" data-spy="scroll" data-target=".navbar-custom">
    <%= render 'layouts/header' %>
    
  


  
    <div>
       <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
   
  </body>
</html>

app/views/static_pages/committees.html.erb
<%= provide(:title, "Committees") %>
<!--committees-->
      <section id="committees" class="home-section">

    <div class="container marginbot-60">
           <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
          
                     <div class="section-heading text-center">
          <h2 class="h-bold">Committees</h2>
          <div class="divider-header"></div>
          
          </div>
        </div>
      </div>
</div>
<!--committee accordion-->
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          <!--panel 1-->
            <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="headingOne">
               <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapse">
                DISEC
                </a>
               </h4>
              </div>
              <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
               <div class="panel-body">
               Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia lacinia mauris, at ultricies leo ornare nec. Vivamus eu est vel felis dignissim tempor. Nulla facilisi. Duis molestie tortor ac tempor volutpat. Phasellus nec mi aliquet, sollicitudin neque eget, consectetur libero. Vestibulum sollicitudin sapien libero, egestas tempus eros scelerisque eu.
               </div>
              </div> 
             </div> 

             <!--panel 2-->
             <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="headingTwo">
               <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapse">
                SOCHUM
                </a>
               </h4>
              </div>
              <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
               <div class="panel-body">
               Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia lacinia mauris, at ultricies leo ornare nec. Vivamus eu est vel felis dignissim tempor. Nulla facilisi. Duis molestie tortor ac tempor volutpat. Phasellus nec mi aliquet, sollicitudin neque eget, consectetur libero. Vestibulum sollicitudin sapien libero, egestas tempus eros scelerisque eu.
               </div>
              </div> 
             </div> 

             <!--panel 3-->
             <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="headingThree">
               <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="true" aria-controls="collapse">
                Crisis
                </a>
               </h4>
              </div>
              <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
               <div class="panel-body">
               Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia lacinia mauris, at ultricies leo ornare nec. Vivamus eu est vel felis dignissim tempor. Nulla facilisi. Duis molestie tortor ac tempor volutpat. Phasellus nec mi aliquet, sollicitudin neque eget, consectetur libero. Vestibulum sollicitudin sapien libero, egestas tempus eros scelerisque eu.
               </div>
              </div> 
             </div> 

             <!--panel 4-->
             <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="headingFour">
               <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="true" aria-controls="collapse">
                Security Council
                </a>
               </h4>
              </div>
              <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
               <div class="panel-body">
               Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia lacinia mauris, at ultricies leo ornare nec. Vivamus eu est vel felis dignissim tempor. Nulla facilisi. Duis molestie tortor ac tempor volutpat. Phasellus nec mi aliquet, sollicitudin neque eget, consectetur libero. Vestibulum sollicitudin sapien libero, egestas tempus eros scelerisque eu.
               </div>
              </div> 
             </div> 

             <!--panel 5-->
             <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="headingFive">
               <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="true" aria-controls="collapse">
                NATO-CIS
                </a>
               </h4>
              </div>
              <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
               <div class="panel-body">
               Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia lacinia mauris, at ultricies leo ornare nec. Vivamus eu est vel felis dignissim tempor. Nulla facilisi. Duis molestie tortor ac tempor volutpat. Phasellus nec mi aliquet, sollicitudin neque eget, consectetur libero. Vestibulum sollicitudin sapien libero, egestas tempus eros scelerisque eu.
               </div>
              </div> 
             </div> 
   </div>
  </div>
 </div>




      </section>
      <!--end committees-->

app/views/static_pages/home.html.erb
<%= provide(:title, "Home") %>

<!-- Section: about -->
    <section id="about" class="home-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          
          <div class="section-heading text-center marginbot-30">
          <h2 class="h-bold">About Us</h2>
          <div class="divider-header"></div>
            </div><!--end about us heading-->
          </div>
        </div>
      </div>

    

    <div class="container marginbot-50">

    
        <div class="row">
    
    
            <div class="col-lg-8 col-lg-offset-2">   
        <div class="text-center">
          <p>
          Lorem ipsum dolor sit amet, vis tale malis tacimates et, graece doctus omnesque ne est, deserunt pertinacia ne nam. Pro eu simul affert referrentur, natum mutat erroribus te his
          </p>
          <p>
          Ne mundi fabulas corrumpit vim, nulla vivendum conceptam eu nam. Ius ex principes complectitur, ex quo duis suscipit. Ius fastidii reprimique no. Sadipscing appellantur pri ad. Oratio moderatius definitiones cum ex, mea ne brute vivendum percipitur. 
          </p>
          <a href="#resources" class="btn btn-skin btn-scroll">Resources</a>
        </div>
            </div>
</div>
</div><!--end container-->
</section>



<!--sec gen address-->
<section id="secgenaddress" class="home-section" style="margin-top:-35px;">

    <div class="container marginbot-60" style="margin-top:-60px;">
           <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
          
                     <div class="section-heading text-center">
          <h2 class="h-bold">Secretary General's Address</h2>
          <div class="divider-header"></div>
          
          </div>
        </div>
      </div>


      <!--sec gen details-->
   <div class="container margintop-50">
 <div class="row">
  <div class="col-sm-4">
   <div class="box">
       <%= image_tag("secgen.jpg", :alt => "Sivan SecGen", :class => "img-responsive img-circle") %>
        <div class="boxContent">
         <h3 class="title">Sivan Chakravarty</h3>
            <span class="post">Secretary General</span>
              <ul class="links">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              </ul>
         </div>          
        </div>
      </div>                                                                                           
   
                                            
           


                        <div class="col-sm-6 col-sm-offset-1">   
                                <div class="text-justify">
          <p>
          Lorem ipsum dolor sit amet, vis tale malis tacimates et, graece doctus omnesque ne est, deserunt pertinacia ne nam. Pro eu simul affert referrentur, natum mutat erroribus te his
          </p>
          <p>
          Ne mundi fabulas corrumpit vim, nulla vivendum conceptam eu nam. Ius ex principes complectitur, ex quo duis suscipit. Ius fastidii reprimique no. Sadipscing appellantur pri ad. Oratio moderatius definitiones cum ex, mea ne brute vivendum percipitur.  Ne mundi fabulas corrumpit vim, nulla vivendum conceptam eu nam. Ius ex principes complectitur, ex quo duis suscipit. Ius fastidii reprimique no. Sadipscing appellantur pri ad. Oratio moderatius definitiones cum ex, mea ne brute vivendum percipitur.  Ne mundi fabulas corrumpit vim, nulla vivendum conceptam eu nam. Ius ex principes complectitur, ex quo duis suscipit. Ius fastidii reprimique no. Sadipscing appellantur pri ad. Oratio moderatius definitiones cum ex, mea ne brute vivendum percipitur. 
          </p>
          <p>  Ne mundi fabulas corrumpit vim, nulla vivendum conceptam eu nam. Ius ex principes complectitur, ex quo duis suscipit. Ius fastidii reprimique no. Sadipscing appellantur pri ad. Oratio moderatius definitiones cum ex, mea ne brute vivendum percipitur. </p>

          </div>

          </div>

          </div>

          </div><!--end row-->

          </section>
<!--end sec gen--> 

<!--begin resources-->
<section id="resources" class="home-section color-dark bg-gray margintop-50">
  <div class="container marginbot-50" style="margin-top:-50px;">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          
          <div class="section-heading text-center">
          <h2 class="h-bold">Resources</h2>
          <div class="divider-header"></div>
            </div><!--end resource heading-->
          </div>
        </div>
      </div>
    

      <!--servicebox-->
<div class="container">
  <div class="row">

    <div class="col-md-4">
      <div class="serviceBox">
    <h3 class="title">Registration</h3>
    <div class="service-icon">
      <i class="fa fa-rocket"></i>
    </div>
    <p class="description"> Lorem ipsum dolor sit amet, vis tale malis tacimates et, graece doctus omnesque ne est, deserunt pertinacia ne nam. Pro eu simul affert referrentur, natum mutat erroribus te his</p>
         <%= link_to "Register now!", registration_path, class: "read" %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="serviceBox">
    <h3 class="title">Study Guides</h3>
    <div class="service-icon">
      <i class="fa fa-book"></i>
    </div>
    <p class="description"> Lorem ipsum dolor sit amet, vis tale malis tacimates et, graece doctus omnesque ne est, deserunt pertinacia ne nam. Pro eu simul affert referrentur, natum mutat erroribus te his</p>
        <%= link_to "Link", studyguide_path, class: "read" %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="serviceBox">
    <h3 class="title">Schedule</h3>
    <div class="service-icon">
      <i class="fa fa-globe"></i>
    </div>
    <p class="description"> Lorem ipsum dolor sit amet, vis tale malis tacimates et, graece doctus omnesque ne est, deserunt pertinacia ne nam. Pro eu simul affert referrentur, natum mutat erroribus te his</p>
         <%= link_to "Details", schedule_path, class: "read" %>
      </div>
   </div>
    
  </div>
 </div>   

</section>
<!--end resource section-->

app/views/static_pages/registration.html.erb
<%= provide(:title, "Registration") %>
<h1>StaticPages#registration</h1>
<p>Find me in app/views/static_pages/registration.html.erb</p>

app/views/static_pages/schedule.html.erb
<%= provide(:title, "Schedule") %>
<h1>StaticPages#schedule</h1>
<p>Find me in app/views/static_pages/schedule.html.erb</p>

app/views/static_pages/studyguide.html.erb
<%= provide(:title, "Study Guides") %>
<h1>StaticPages#studyguide</h1>
<p>Find me in app/views/static_pages/studyguide.html.erb</p>